version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092" # Expone el puerto interno para comunicación dentro de la red
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - broker
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
    networks:
      - kafka-network

  api-gateway:
    build: ./api-gateway
    ports:
      - '3000:3000'
    environment:
      KAFKA_BROKERS: broker:29092 # Usa el nombre del servicio y el puerto interno
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - kafka-network

  auth-service:
    build: ./auth-service
    environment:
      KAFKA_BROKERS: broker:29092 # Usa el nombre del servicio y el puerto interno
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - kafka-network

  user-service:
    build: ./user-service
    environment:
      KAFKA_BROKERS: broker:29092 # Usa el nombre del servicio y el puerto interno
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - kafka-network

  log-service:
    build: ./log-service
    environment:
      KAFKA_BROKERS: broker:29092 # Usa el nombre del servicio y el puerto interno
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge